
CREATE SCHEMA `ElectroTech` DEFAULT CHARACTER SET utf8;

CREATE TABLE `marca` ( 
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT,
  `createAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `producto` ( 
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT,
  `imagen` VARCHAR(255), 
  `precio` DECIMAL(10,2) NOT NULL,
  `categoria` VARCHAR(50),
  `estado` ENUM('activo', 'inactivo') DEFAULT 'activo',
  `marcaId` INT NOT NULL,
  `createAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`marcaId`) REFERENCES `marca`(`id`) ON DELETE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

