
CREATE SCHEMA `productosdb` DEFAULT CHARACTER SET utf8;

CREATE TABLE `marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT,
  `createAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT,
  `precio` DECIMAL(10,2) NOT NULL,
  `tipo` VARCHAR(50),
  `status` ENUM('active', 'inactive') DEFAULT 'active',
  `marcaId` INT NOT NULL,  -- Aquí referenciamos a la marca
  `createAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`marcaId`) REFERENCES `marcas`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
